name: "Continuous Integration Continuous Delivery"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build-deploy-CutterManagementSystem-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dotnet setup
        uses: actions/setup-dotnet@v3
        with:
              dotnet-version: '8.0.*'
  
      - name: Restoring dependencies
        run: dotnet restore CutterManagementSystem.sln -r win-x64

      - name: Building solution
        run: dotnet build CutterManagement.UI.Desktop/CutterManagement.UI.Desktop.csproj -c Release -r win-x64 --no-restore

      - name: Publishing application
        run: dotnet publish CutterManagement.UI.Desktop/CutterManagement.UI.Desktop.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true --no-build -o ./CutterManagementSystem-${{ env.RELEASE_VERSION }}

      - name: Zipping the published folder (using powershell)
        shell: pwsh
        run: Compress-Archive -path "CutterManagementSystem-${{ env.RELEASE_VERSION }}" -DestinationPath "CutterManagementSystem-${{ env.RELEASE_VERSION }}.zip"

      - name: Uploading the zipped folder as a release
        uses: softprops/action-gh-release@v1
        with:
          files: CutterManagementSystem-${{ env.RELEASE_VERSION }}.zip
          name: "Cutter-Management-System ${{ env.RELEASE_VERSION }}"
          tag_name: ${{ github.ref_name }}